--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ApexieDevelopment/Knock
build-by-default: true
branches:
- stable
projects:
  KnockbackFFA:
    path: ""
    icon: "assets/icon.png"
    lint:
      phpstan: false
    libs:
    - src: "CortexPE/Commando/Commando"
      branch: "PM4"
      version: ^3.0.0
    - src: "jojoe77777/FormAPI/libFormAPI"
      version: ^1.3.0
    - src: "ifera-mc/UpdateNotifier/UpdateNotifier"
      branch: "API-4.0.0"
      version: ^2.2.0
...