--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ApexieDevelopment/Knock
build-by-default: true
branches:
- stable
projects:
  KnockbackFFA:
    path: ""
    icon: "assets/icon.png"
    lint:
      phpstan: false
    libs:
    - src: "CortexPE/Commando/Commando"
      branch: "master"
      version: ^3.2.0
    - src: "WolvesFortress/FormAPI/libFormAPI"
      version: ^1.3.0
    - src: "ifera-mc/UpdateNotifier/UpdateNotifier"
      branch: "master"
      version: ^3.0.0
...
