name: KnockbackFFA
main: ItzLightyHD\KnockbackFFA\Loader
api: 5.3.0
version: 1.6.0
authors:
  - ItzLightyHD
  - OwoNico
  - MBG
permissions:
  knockbackffa.customize:
    default: op
  knockbackffa.player:
    default: true
